### PR TITLE
Getting rid of old dust project.pxi file

### PR DESCRIPTION
**Pull request by jellea**
Throws error when present:

```
Error:  in internal function load-file

in internal function load-reader

Running: (require dust.project :as p)
in /Users/jelle/dev/github/pixie/dust/run.pxi at 1:1
(require dust.project :as p)
^
in pixie function _toplevel_

in internal function load-ns

in internal function load-file

in internal function load-reader

Running: (defproject dust 0.1.0-alpha :description Magic fairy dust for Pixie :dependencies [])
in /Users/jelle/dev/github/pixie/dust/project.pxi at 1:1
(defproject dust "0.1.0-alpha"
^
in pixie function _toplevel_

in /Users/jelle/dev/github/pixie/dust/project.pxi at 1:2
(defproject dust "0.1.0-alpha"
 ^
RuntimeException: :pixie.stdlib/AssertionException Var defproject is undefined
```

### CODE REVIEW

**Comment by heyLu** [comment]
Which command threw the error?  I tried `dust` and `dust repl` in the top-level directory of the repository (with a freshly compiled `pixie-vm`) and didn't get an error.

**Comment by jellea** [comment]
`dust` and `dust repl` don't throw anything, but for example `dust test` and `dust get-deps` do. In the dust project, but also other projects. Have a fresh `pixie-vm` of yesterday.

**Comment by heyLu** [comment]
Which project did you run this on?  I tried it on dust itself, the `html` and `test` examples, and `hiccup.pxi`, and didn't get the error.  (Sorry about the trouble, but this seems weird, not sure what the actual problem is.)

My `pixie-vm` is from today, i.e. current master.

**Comment by jellea** [comment]
Tried it on `test` example, `hiccup.pxi` and my own project. Let me pull in current `pixie-vm` master and report back.

**Comment by jellea** [comment]
Ok both `dust` and `pixie-vm` current master now and did a clean compile, but still getting it... Do you have the correct pypy version in place? It's fixed now to an older version due to OS X El capitan issues I believe. I have the feeling though this has nothing to do with `pixie-vm` itself.

**Comment by jellea** [comment]
Ok found whats causing this exception. I had the dust repo within the pixie-vm repo; moved it a level up and it seems to be gone now.

**Pull request closed without merging**
